### ISSUE TITLE
Version number hasn't been bumped since 0.1.0

### ISSUE THREAD

**Issue by elazar** [vinkla/climb#8] opened 2015-09-15 13:13 UTC
See [this line](https://github.com/vinkla/climb/blob/26957c798379815c3395f241e450a54a36735987/src/Application.php#L29).

**Comment by vinkla** [comment] 2015-09-15 13:28
Thanks. It bugs me that I have to do this manually.

**Comment by elazar** [comment] 2015-09-15 13:33
GitHub has a [Releases API](https://developer.github.com/v3/repos/releases/#create-a-release). You could script the process using that. There may even already be a tool out there that does this, but I'm not familiar with a specific one offhand.

**Comment by vinkla** [comment] 2015-09-15 13:35
The problem is if the user hasn't updated to the latest version then we have no idea which version they are using.

**Comment by elazar** [comment] 2015-09-15 13:54
Sorry, to clarify, here's how this scripted release process would work.

First, do a one-time commit and push to `master` with a change to `Application.php` where `Application::VERSION` is set to a placeholder value.

Then, your release script would accept a version and do something like this:
1. Check a local clone of the repo out to master.
2. Replace the version placeholder in `Application.php` with the specified version.
3. Create an archive of the repo's state using `tar` and `gzip`. Be sure to exclude the `.git` directory.
4. Push the archive to GitHub as a [release asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

Does that make more sense?

**Comment by vinkla** [comment] 2015-09-15 13:57
Yes, thanks for the clarification. Will look into this when I've a more time to spare. Right now I can update it manually but in the future something like this would be really good to have!

**Comment by vinkla** [comment] 2015-09-15 13:59
Fixed in b1149bf473d53db7e996b985bf7f29f52a674547

**Closed by vinkla** 2015-09-15 13:59 UTC
